using Unity.Burst;
using Unity.Collections;
using Unity.Entities;

/// <summary>
/// Drives the sustained attack loop for player-commanded minion entities.
///
/// After MinionOrderExecutionSystem enables Attack + Target on a minion,
/// this system keeps the loop running:
///   • Re-enables Attack each tick once AttackCooldown reaches 0.
///   • Monitors the target for death — cleans up and releases the unit
///     back to AI when the target is gone.
///
/// AttackResolutionSystem (CombatResolutionSystemGroup) does the actual damage
/// and DISABLES Attack after each hit. This system re-enables it for the next hit.
///
/// Only manages minions whose PlayerControlled is enabled, so
/// MinionAutoCounterSystem can take over cleanly by simply disabling it.
///
/// In the single-entity model, PlayerControlled/NeedsAction/Attack/Target all
/// live on the same unit entity — no BrainLink lookup needed.
/// </summary>
[BurstCompile]
[UpdateInGroup(typeof(AIExecutionSystemGroup))]
public partial struct MinionAttackExecutionSystem : ISystem
{
    private ComponentLookup<Alive>  aliveLookup;
    private ComponentLookup<Attack> attackLookup;
    private ComponentLookup<Target> targetLookup;

    [BurstCompile]
    public void OnCreate(ref SystemState state)
    {
        state.RequireForUpdate<GameSceneTag>();
        aliveLookup  = state.GetComponentLookup<Alive>(true);
        attackLookup = state.GetComponentLookup<Attack>(false);
        targetLookup = state.GetComponentLookup<Target>(false);
    }

    [BurstCompile]
    public void OnUpdate(ref SystemState state)
    {
        aliveLookup.Update(ref state);
        attackLookup.Update(ref state);
        targetLookup.Update(ref state);

        state.Dependency = new MinionAttackExecutionJob
        {
            aliveLookup  = aliveLookup,
            attackLookup = attackLookup,
            targetLookup = targetLookup,
        }.Schedule(state.Dependency);
    }

    [BurstCompile]
    public void OnDestroy(ref SystemState state) { }
}

// Iterates minion entities with Target enabled (in an attack state).
// All AI state and combat state live on the same entity.
//
// Target is read via targetLookup (not as an Execute parameter) to avoid the
// DOTS aliasing error that occurs when a writable ComponentLookup<Target> and a
// read-only ComponentTypeHandle<Target> (generated by "in Target" in the signature)
// both reference the same component type.
[BurstCompile]
[WithAll(typeof(Minion), typeof(Target))]
[WithPresent(typeof(Attack), typeof(PlayerControlled), typeof(NeedsAction))]
public partial struct MinionAttackExecutionJob : IJobEntity
{
    [ReadOnly] public ComponentLookup<Alive>  aliveLookup;
    public            ComponentLookup<Attack> attackLookup;
    public            ComponentLookup<Target> targetLookup;

    public void Execute(
        Entity entity,
        in AttackCooldown cooldown,
        EnabledRefRW<PlayerControlled> playerControlledEnabled,
        EnabledRefRW<NeedsAction> needsActionEnabled)
    {
        // Only manage player-ordered attacks — AI attacks handle themselves.
        if (!playerControlledEnabled.ValueRO) return;

        // Read target entity via lookup to avoid aliasing with the WithAll<Target> filter.
        if (!targetLookup.TryGetComponent(entity, out Target target)) return;

        Entity targetEntity = target.entity;

        // Target gone or dead → clean up and release to AI.
        bool targetAlive = aliveLookup.HasComponent(targetEntity) &&
                           aliveLookup.IsComponentEnabled(targetEntity);

        if (!targetAlive)
        {
            targetLookup.SetComponentEnabled(entity, false);

            if (attackLookup.HasComponent(entity))
                attackLookup.SetComponentEnabled(entity, false);

            playerControlledEnabled.ValueRW = false;
            needsActionEnabled.ValueRW      = true;
            return;
        }

        // Target still alive — re-enable Attack once the cooldown has expired.
        if (cooldown.timer <= 0f && attackLookup.HasComponent(entity))
            attackLookup.SetComponentEnabled(entity, true);
    }
}
