using Unity.Burst;
using Unity.Entities;
using Unity.Collections;

/// <summary>
/// Drives the sustained attack loop for player-commanded minion bodies.
///
/// After MinionOrderExecutionSystem enables Attack + Target on a minion body,
/// this system keeps the loop running:
///   • Re-enables Attack each tick once AttackCooldown reaches 0.
///   • Monitors the target for death — cleans up body state and releases the
///     brain back to AI when the target is gone.
///
/// AttackResolutionSystem (CombatResolutionSystemGroup) does the actual damage
/// and DISABLES Attack after each hit. This system re-enables it for the next hit.
///
/// Only manages minions whose brain still has PlayerControlled enabled, so
/// MinionAutoCounterSystem can take over cleanly by simply disabling PlayerControlled.
/// </summary>
[BurstCompile]
[UpdateInGroup(typeof(AIExecutionSystemGroup))]
public partial struct MinionAttackExecutionSystem : ISystem
{
    private ComponentLookup<Alive>            aliveLookup;
    private ComponentLookup<Attack>           attackLookup;
    private ComponentLookup<Target>           targetLookup;
    private ComponentLookup<PlayerControlled> playerControlledLookup;
    private ComponentLookup<NeedsAction>      needsActionLookup;

    [BurstCompile]
    public void OnCreate(ref SystemState state)
    {
        state.RequireForUpdate<GameSceneTag>();
        aliveLookup            = state.GetComponentLookup<Alive>(true);
        attackLookup           = state.GetComponentLookup<Attack>(false);
        targetLookup           = state.GetComponentLookup<Target>(false);
        playerControlledLookup = state.GetComponentLookup<PlayerControlled>(false);
        needsActionLookup      = state.GetComponentLookup<NeedsAction>(false);
    }

    [BurstCompile]
    public void OnUpdate(ref SystemState state)
    {
        aliveLookup.Update(ref state);
        attackLookup.Update(ref state);
        targetLookup.Update(ref state);
        playerControlledLookup.Update(ref state);
        needsActionLookup.Update(ref state);

        state.Dependency = new MinionAttackExecutionJob
        {
            aliveLookup            = aliveLookup,
            attackLookup           = attackLookup,
            targetLookup           = targetLookup,
            playerControlledLookup = playerControlledLookup,
            needsActionLookup      = needsActionLookup,
        }.Schedule(state.Dependency);
    }

    [BurstCompile]
    public void OnDestroy(ref SystemState state) { }
}

// Iterates minion bodies with Target enabled (in an attack state).
// Cross-entity reads (brain PlayerControlled, target Alive) and writes
// (Attack/Target on body, PlayerControlled/NeedsAction on brain) are safe
// with Schedule (single-threaded).
//
// Target is read via targetLookup (not as an Execute parameter) to avoid the
// DOTS aliasing error that occurs when a writable ComponentLookup<T> and a
// read-only ComponentTypeHandle<T> (generated by "in T" in the signature) both
// reference the same component type.
[BurstCompile]
[WithAll(typeof(Minion), typeof(Target))]
public partial struct MinionAttackExecutionJob : IJobEntity
{
    [ReadOnly] public ComponentLookup<Alive>            aliveLookup;
    public            ComponentLookup<Attack>           attackLookup;
    public            ComponentLookup<Target>           targetLookup;
    public            ComponentLookup<PlayerControlled> playerControlledLookup;
    public            ComponentLookup<NeedsAction>      needsActionLookup;

    // Filtered to: Minion bodies + Target enabled (WithAll) + BrainLink + AttackCooldown present.
    public void Execute(
        Entity bodyEntity,
        in BrainLink brainLink,
        in AttackCooldown cooldown)
    {
        Entity brain = brainLink.brain;
        if (brain == Entity.Null) return;

        // Only manage player-ordered attacks — AI attacks handle themselves.
        if (!playerControlledLookup.HasComponent(brain)) return;
        if (!playerControlledLookup.IsComponentEnabled(brain)) return;

        // Read target entity through the lookup to avoid aliasing with the WithAll filter.
        if (!targetLookup.TryGetComponent(bodyEntity, out Target targetComponent))
            return;

        Entity targetEntity = targetComponent.entity;

        // Target gone or dead → clean up body state and release brain to AI.
        bool targetAlive = aliveLookup.HasComponent(targetEntity)
                        && aliveLookup.IsComponentEnabled(targetEntity);

        if (!targetAlive)
        {
            targetLookup.SetComponentEnabled(bodyEntity, false);

            if (attackLookup.HasComponent(bodyEntity))
                attackLookup.SetComponentEnabled(bodyEntity, false);

            playerControlledLookup.SetComponentEnabled(brain, false);

            if (needsActionLookup.HasComponent(brain))
                needsActionLookup.SetComponentEnabled(brain, true);

            return;
        }

        // Target still alive — sustain the attack loop by re-enabling Attack
        // once AttackResolutionSystem has finished its cooldown.
        if (cooldown.timer <= 0f && attackLookup.HasComponent(bodyEntity))
            attackLookup.SetComponentEnabled(bodyEntity, true);
    }
}
