// Copyright (c) 2026 Spencer Park. All rights reserved.

using System;
using System.Collections.Generic;
using System.Text;
using DotsAnimationToolkit.Authoring;
using UnityEditor;

namespace DotsAnimationToolkit.Editor
{
    /// <summary>Writes a ready-to-edit host ISystem that reads animation events and switches over their routes. Host code, never package code.</summary>
    public static class AnimEventConsumerStubBuilder
    {
        public const string FolderPrefsKey = "DotsAnimationToolkit.Events.StubFolder";

        private const string SystemSuffix = "AnimEventSystem";

        public static string SystemTypeName(string systemName)
        {
            string sanitizedName = ConstantsGenerator.SanitizeIdentifier(systemName);
            if (string.IsNullOrEmpty(sanitizedName))
            {
                sanitizedName = "Project";
            }
            return sanitizedName.EndsWith(SystemSuffix, StringComparison.Ordinal)
                ? sanitizedName
                : sanitizedName + SystemSuffix;
        }

        public static string BuildSource(string systemName, IReadOnlyList<AnimEventRouteKind> kindsUsed)
        {
            string systemTypeName = SystemTypeName(systemName);
            string jobTypeName = systemTypeName.Substring(0, systemTypeName.Length - SystemSuffix.Length) + "Job";

            List<AnimEventRouteKind> kindsToEmit = new List<AnimEventRouteKind>();
            if (kindsUsed == null || kindsUsed.Count == 0)
            {
                kindsToEmit.Add(AnimEventRouteKind.Sound);
                kindsToEmit.Add(AnimEventRouteKind.Vfx);
                kindsToEmit.Add(AnimEventRouteKind.Ragdoll);
                kindsToEmit.Add(AnimEventRouteKind.ShaderView);
                kindsToEmit.Add(AnimEventRouteKind.Custom);
            }
            else
            {
                for (int kindIndex = 0; kindIndex < kindsUsed.Count; kindIndex++)
                {
                    kindsToEmit.Add(kindsUsed[kindIndex]);
                }
            }

            StringBuilder source = new StringBuilder();
            source.Append("// Generated by the DOTS Animation Toolkit Events tab.\n");
            source.Append("// This is your code now: regenerating overwrites it.\n");
            source.Append("// The package never handles a route itself — every case below is yours to fill in.\n");
            source.Append("using Unity.Burst;\n");
            source.Append("using Unity.Collections;\n");
            source.Append("using Unity.Entities;\n");
            source.Append("using DotsAnimationToolkit;\n");
            source.Append("\n");
            source.Append("[BurstCompile]\n");
            source.Append("// Place after EventEmissionSystem\n");
            source.Append("public partial struct ").Append(systemTypeName).Append(" : ISystem\n");
            source.Append("{\n");
            source.Append("    [BurstCompile]\n");
            source.Append("    public void OnCreate(ref SystemState state)\n");
            source.Append("    {\n");
            source.Append("        state.RequireForUpdate<AnimEventRouting>();\n");
            source.Append("    }\n");
            source.Append("\n");
            source.Append("    [BurstCompile]\n");
            source.Append("    public void OnUpdate(ref SystemState state)\n");
            source.Append("    {\n");
            source.Append("        BlobAssetReference<AnimEventRoutingBlob> routingBlob =\n");
            source.Append("            SystemAPI.GetSingleton<AnimEventRouting>().Value;\n");
            source.Append("        if (!routingBlob.IsCreated) return;\n");
            source.Append("\n");
            source.Append("        state.Dependency = new ").Append(jobTypeName).Append("\n");
            source.Append("        {\n");
            source.Append("            routingBlob = routingBlob,\n");
            source.Append("        }.ScheduleParallel(state.Dependency);\n");
            source.Append("    }\n");
            source.Append("}\n");
            source.Append("\n");
            source.Append("[BurstCompile]\n");
            source.Append("[WithAll(typeof(AnimEventsPending))]\n");
            source.Append("public partial struct ").Append(jobTypeName).Append(" : IJobEntity\n");
            source.Append("{\n");
            source.Append("    [ReadOnly] public BlobAssetReference<AnimEventRoutingBlob> routingBlob;\n");
            source.Append("\n");
            source.Append("    public void Execute(in DynamicBuffer<AnimEventOutput> events)\n");
            source.Append("    {\n");
            source.Append("        for (int eventIndex = 0; eventIndex < events.Length; eventIndex++)\n");
            source.Append("        {\n");
            source.Append("            AnimEventOutput animEvent = events[eventIndex];\n");
            source.Append("            if (!AnimEventRoutingApi.TryGetRoutes(\n");
            source.Append("                ref routingBlob.Value, animEvent.eventKey, out int routeStart, out int routeCount))\n");
            source.Append("            {\n");
            source.Append("                continue;\n");
            source.Append("            }\n");
            source.Append("\n");
            source.Append("            for (int routeIndex = routeStart; routeIndex < routeStart + routeCount; routeIndex++)\n");
            source.Append("            {\n");
            source.Append("                AnimEventRouteBlob route = routingBlob.Value.routes[routeIndex];\n");
            source.Append("                switch (route.kind)\n");
            source.Append("                {\n");
            for (int kindIndex = 0; kindIndex < kindsToEmit.Count; kindIndex++)
            {
                AnimEventRouteKind kind = kindsToEmit[kindIndex];
                source.Append("                    case AnimEventRouteKind.").Append(kind).Append(":\n");
                source.Append("                        // TODO: ").Append(RouteIdMeaningComment(kind)).Append("\n");
                source.Append("                        break;\n");
            }
            source.Append("                    default:\n");
            source.Append("                        break;\n");
            source.Append("                }\n");
            source.Append("            }\n");
            source.Append("        }\n");
            source.Append("    }\n");
            source.Append("}\n");

            return source.ToString();
        }

        private static string RouteIdMeaningComment(AnimEventRouteKind kind)
        {
            switch (kind)
            {
                case AnimEventRouteKind.Sound:
                    return "route.routeId names a sound to play; look it up in your sound library.";
                case AnimEventRouteKind.Vfx:
                    return "route.routeId names a visual effect to spawn.";
                case AnimEventRouteKind.Ragdoll:
                    return "route.routeId names a ragdoll response, such as a launch force preset.";
                case AnimEventRouteKind.ShaderView:
                    return "route.routeId names a shader view or material state to switch to.";
                case AnimEventRouteKind.Custom:
                    return "route.routeId is project-defined; interpret it however this event needs.";
                default:
                    return "route.routeId meaning is project-defined for this kind.";
            }
        }

        public static List<AnimEventRouteKind> CollectKindsUsed(AnimEventRoutingAsset routingAsset)
        {
            List<AnimEventRouteKind> distinctKinds = new List<AnimEventRouteKind>();
            if (routingAsset == null || routingAsset.routes == null)
            {
                return distinctKinds;
            }

            SortedSet<AnimEventRouteKind> seenKinds = new SortedSet<AnimEventRouteKind>();
            for (int routeIndex = 0; routeIndex < routingAsset.routes.Count; routeIndex++)
            {
                AnimEventRoute route = routingAsset.routes[routeIndex];
                if (route == null)
                {
                    continue;
                }
                seenKinds.Add(route.kind);
            }

            foreach (AnimEventRouteKind kind in seenKinds)
            {
                distinctKinds.Add(kind);
            }
            return distinctKinds;
        }

        public static string WriteToFolder(string folderPath, string systemName, IReadOnlyList<AnimEventRouteKind> kindsUsed)
        {
            string filePath = folderPath.Replace('\\', '/').TrimEnd('/') + "/" + SystemTypeName(systemName) + ".cs";
            ConstantsGenerator.WriteGeneratedFile(filePath, BuildSource(systemName, kindsUsed));
            EditorPrefs.SetString(FolderPrefsKey, ConstantsGenerator.ToStorablePath(folderPath));
            return filePath;
        }
    }
}
