// Copyright (c) 2026 Spencer Park. All rights reserved.

using System.Collections.Generic;
using DotsAnimationToolkit;
using DotsAnimationToolkit.Authoring;
using UnityEditor;
using UnityEditor.UIElements;
using UnityEngine;
using UnityEngine.UIElements;

namespace DotsAnimationToolkit.Editor
{
    /// <summary>
    /// Read-only inspector for <see cref="VatTextureSetAsset"/>: bake statistics, per-clip frame
    /// ranges, and socket track counts, plus a shortcut back to the VAT Bake window.
    /// </summary>
    [CustomEditor(typeof(VatTextureSetAsset))]
    public sealed class VatTextureSetAssetEditor : UnityEditor.Editor
    {
        // Fallback bytes/texel for a format the baker never emits — an approximate estimate beats
        // silently guessing one of the two real formats and reporting a number that looks exact.
        private const int FallbackBytesPerTexel = 4;

        private const float TableRowHeight = 20f;
        private const float TableMaxHeight = 200f;

        /// <inheritdoc />
        public override VisualElement CreateInspectorGUI()
        {
            // Values render as Label text, never a bound PropertyField — a disabled field still
            // looks clickable, which is the wrong impression for a baker-only generated asset.
            VatTextureSetAsset textureSet = target as VatTextureSetAsset;

            VisualElement root = new VisualElement();
            root.style.paddingTop = 4f;

            root.Add(BuildGeneratedAssetNotice());

            if (textureSet == null)
            {
                return root;
            }

            root.Add(BuildSectionHeading("Overview"));
            root.Add(BuildOverviewSection(textureSet));

            root.Add(BuildSectionHeading("Estimated GPU Memory"));
            root.Add(BuildMemorySection(textureSet));

            root.Add(BuildSectionHeading("Clip Ranges"));
            root.Add(BuildClipRangeSection(textureSet));

            root.Add(BuildSectionHeading("Socket Tracks"));
            root.Add(BuildSocketTrackSection(textureSet));

            root.Add(BuildSectionHeading("Staleness"));
            root.Add(BuildStalenessSection(textureSet));

            root.Add(BuildSectionHeading("Rebake"));
            root.Add(BuildRebakeSection());

            return root;
        }

        // -----------------------------------------------------------------------------------
        // Static chrome.
        // -----------------------------------------------------------------------------------

        private static Label BuildSectionHeading(string text)
        {
            Label heading = new Label(text);
            heading.style.unityFontStyleAndWeight = FontStyle.Bold;
            heading.style.marginTop = 10f;
            heading.style.marginBottom = 2f;
            return heading;
        }

        private static HelpBox BuildGeneratedAssetNotice()
        {
            return new HelpBox(
                "Generated by the VAT Texture Baker. Every field on this asset is written by the "
                + "bake and is not meant to be hand-edited: changing a frame range or a count here "
                + "still looks valid to Unity but produces a set that no longer matches its own "
                + "textures, and nothing downstream detects that — VatMaterialSystem just holds "
                + "whatever frame the mismatch lands on. Use \"Open VAT Baker\" below to regenerate "
                + "this asset instead of editing it.",
                HelpBoxMessageType.Info);
        }

        // -----------------------------------------------------------------------------------
        // Overview.
        // -----------------------------------------------------------------------------------

        private static VisualElement BuildOverviewSection(VatTextureSetAsset textureSet)
        {
            VisualElement container = new VisualElement();

            container.Add(new Label("Flavor:  " + textureSet.flavor.ToString()));
            container.Add(new Label("Schema Version:  " + textureSet.schemaVersion.ToString()));

            Label setKeyLabel = new Label("Set Key:  0x" + textureSet.SetKey.ToString("X16"));
            setKeyLabel.selection.isSelectable = true;
            container.Add(setKeyLabel);

            container.Add(BuildPartsList(textureSet));

            return container;
        }

        // Per-part numbers replaced the set's former singular texture-width/rows-per-frame/count
        // fields when a set could bake more than one target's textures.
        private static VisualElement BuildPartsList(VatTextureSetAsset textureSet)
        {
            VisualElement container = new VisualElement();
            List<VatPartTextures> parts = textureSet.parts;

            if (parts == null || parts.Count == 0)
            {
                Label emptyLabel = new Label("No parts baked.");
                emptyLabel.style.marginTop = 4f;
                container.Add(emptyLabel);
                return container;
            }

            for (int partIndex = 0; partIndex < parts.Count; partIndex++)
            {
                container.Add(BuildPartBox(parts[partIndex], textureSet.flavor));
            }

            return container;
        }

        private static VisualElement BuildPartBox(VatPartTextures part, VatFlavor flavor)
        {
            VisualElement box = new VisualElement();
            box.AddToClassList("toolkit-box");
            ApplyBoxFallbackStyle(box);

            VisualElement header = new VisualElement();
            header.AddToClassList("toolkit-box__header");
            ApplyBoxHeaderFallbackStyle(header);

            Label titleLabel = new Label(PartDisplayName(part));
            titleLabel.AddToClassList("toolkit-box__title");
            titleLabel.style.flexGrow = 1f;
            titleLabel.style.unityFontStyleAndWeight = FontStyle.Bold;
            header.Add(titleLabel);

            Label targetLabel = new Label(
                part.targetId == 0u ? "(untargeted)" : "0x" + part.targetId.ToString("X8"));
            header.Add(targetLabel);

            box.Add(header);

            VisualElement body = new VisualElement();
            body.AddToClassList("toolkit-box__body");
            body.style.paddingLeft = 6f;
            body.style.paddingTop = 2f;

            body.Add(new Label("Flavor:  " + flavor.ToString()));

            Label countLabel = flavor == VatFlavor.BoneMatrix
                ? new Label("Bone Count:  " + part.boneCount.ToString())
                : new Label("Vertex Count:  " + part.vertexCount.ToString());
            body.Add(countLabel);

            body.Add(new Label(
                "Texture Width:  " + part.textureWidth.ToString()
                + "     Rows / Frame:  " + part.rowsPerFrame.ToString()));

            body.Add(new Label(
                "Runtime Mesh:  " + (part.runtimeMesh != null ? part.runtimeMesh.name : "(none)")));

            box.Add(body);
            return box;
        }

        private static string PartDisplayName(VatPartTextures part)
        {
            return string.IsNullOrEmpty(part.displayName) ? "(unnamed part)" : part.displayName;
        }

        // No shared USS is loaded into this inspector, so the toolkit-box classes above carry no
        // styling on their own — these fallbacks reproduce the boxed look inline.
        private static void ApplyBoxFallbackStyle(VisualElement box)
        {
            box.style.marginTop = 6f;
            box.style.marginBottom = 6f;
            box.style.paddingBottom = 4f;
            box.style.borderTopWidth = 1f;
            box.style.borderBottomWidth = 1f;
            box.style.borderLeftWidth = 1f;
            box.style.borderRightWidth = 1f;
            Color borderColor = new Color(0f, 0f, 0f, 0.35f);
            box.style.borderTopColor = borderColor;
            box.style.borderBottomColor = borderColor;
            box.style.borderLeftColor = borderColor;
            box.style.borderRightColor = borderColor;
            box.style.borderTopLeftRadius = 3f;
            box.style.borderTopRightRadius = 3f;
            box.style.borderBottomLeftRadius = 3f;
            box.style.borderBottomRightRadius = 3f;
        }

        private static void ApplyBoxHeaderFallbackStyle(VisualElement header)
        {
            header.style.flexDirection = FlexDirection.Row;
            header.style.alignItems = Align.Center;
            header.style.paddingLeft = 4f;
            header.style.paddingRight = 2f;
            header.style.paddingTop = 2f;
            header.style.paddingBottom = 2f;
            header.style.backgroundColor = new Color(0f, 0f, 0f, 0.12f);
        }

        // -----------------------------------------------------------------------------------
        // Estimated GPU memory.
        // -----------------------------------------------------------------------------------

        private static VisualElement BuildMemorySection(VatTextureSetAsset textureSet)
        {
            VisualElement container = new VisualElement();
            List<VatPartTextures> parts = textureSet.parts;

            if (parts == null || parts.Count == 0)
            {
                container.Add(new Label("No parts baked."));
                return container;
            }

            long totalBytes = 0L;
            for (int partIndex = 0; partIndex < parts.Count; partIndex++)
            {
                VatPartTextures part = parts[partIndex];

                Label partLabel = new Label(PartDisplayName(part) + ":");
                partLabel.style.unityFontStyleAndWeight = FontStyle.Bold;
                partLabel.style.marginTop = partIndex == 0 ? 0f : 6f;
                container.Add(partLabel);

                Texture2D primaryTexture = textureSet.flavor == VatFlavor.BoneMatrix
                    ? part.boneTexture
                    : part.positionTexture;
                string primaryLabel = textureSet.flavor == VatFlavor.BoneMatrix
                    ? "Bone Texture"
                    : "Position Texture";

                totalBytes += AddTextureMemoryRow(container, primaryLabel, primaryTexture);
                totalBytes += AddTextureMemoryRow(container, "Normal Texture", part.normalTexture);
            }

            if (totalBytes == 0L)
            {
                container.Add(new Label("No textures assigned."));
            }

            Label totalLabel = new Label("Total:  " + FormatBytes(totalBytes));
            totalLabel.style.unityFontStyleAndWeight = FontStyle.Bold;
            totalLabel.style.marginTop = 4f;
            container.Add(totalLabel);

            Label assumptionNote = new Label(
                "Estimated as width x height x bytes-per-texel for each texture's own TextureFormat. "
                + "VatTextureBaker.CreateTexture writes RGBAHalf (8 bytes/texel) unless the bake used "
                + "Full Precision, which writes RGBAFloat (16 bytes/texel) — those are the only two "
                + "formats the baker ever emits (Editor/VatBaking/VatTextureBaker.cs, Bake()). Any "
                + "other format reaching this inspector falls back to a conservative "
                + FallbackBytesPerTexel.ToString() + " bytes/texel rather than pretending certainty "
                + "this asset does not have.");
            assumptionNote.style.whiteSpace = WhiteSpace.Normal;
            assumptionNote.style.opacity = 0.7f;
            assumptionNote.style.marginTop = 2f;
            container.Add(assumptionNote);

            return container;
        }

        private static long AddTextureMemoryRow(VisualElement container, string label, Texture2D texture)
        {
            if (texture == null)
            {
                return 0L;
            }
            long byteCount = (long)texture.width * texture.height * BytesPerTexel(texture.format);
            Label rowLabel = new Label(
                label + "  (" + texture.format.ToString() + ", " + texture.width.ToString() + "x"
                + texture.height.ToString() + "):  " + FormatBytes(byteCount));
            container.Add(rowLabel);
            return byteCount;
        }

        private static int BytesPerTexel(TextureFormat format)
        {
            switch (format)
            {
                case TextureFormat.RGBAHalf:
                    // 4 channels x 16-bit float each.
                    return 8;
                case TextureFormat.RGBAFloat:
                    // 4 channels x 32-bit float each.
                    return 16;
                default:
                    return FallbackBytesPerTexel;
            }
        }

        private static string FormatBytes(long byteCount)
        {
            double megabytes = byteCount / (1024.0 * 1024.0);
            return megabytes.ToString("0.00") + " MB";
        }

        // -----------------------------------------------------------------------------------
        // Clip ranges.
        // -----------------------------------------------------------------------------------

        private static VisualElement BuildClipRangeSection(VatTextureSetAsset textureSet)
        {
            VisualElement container = new VisualElement();
            List<VatClipRange> clipRanges = textureSet.clipRanges;

            if (clipRanges == null || clipRanges.Count == 0)
            {
                container.Add(new Label("No clip ranges baked."));
                return container;
            }

            int totalFrames = 0;
            for (int rangeIndex = 0; rangeIndex < clipRanges.Count; rangeIndex++)
            {
                totalFrames += clipRanges[rangeIndex].frameCount;
            }
            Label summary = new Label(
                clipRanges.Count.ToString() + " clip(s), " + totalFrames.ToString() + " total frame(s).");
            summary.style.marginBottom = 4f;
            container.Add(summary);

            float[] columnWidths = { 150f, 140f, 90f, 90f, 60f };
            container.Add(BuildTableHeaderRow(
                new string[] { "Clip Id", "Target", "Frame Start", "Frame Count", "FPS" }, columnWidths));

            ListView listView = new ListView { fixedItemHeight = TableRowHeight };
            listView.itemsSource = clipRanges;
            listView.makeItem = () => BuildTableRow(columnWidths);
            listView.bindItem = (VisualElement element, int index) =>
                BindClipRangeRow(element, clipRanges[index], textureSet);
            listView.style.height = Mathf.Min(TableRowHeight * clipRanges.Count, TableMaxHeight);
            listView.Rebuild();
            container.Add(listView);

            return container;
        }

        /// <summary>
        /// Target reads "(untargeted)" for a clip-wide range baked from <c>ClipAsset.vatSource</c>
        /// (<see cref="VatClipRange.targetId"/> <c>== 0</c>) and the raw hex id otherwise, with the
        /// resolved part's display name appended so the range can be traced to its textures.
        /// </summary>
        private static void BindClipRangeRow(
            VisualElement rowElement, VatClipRange clipRange, VatTextureSetAsset textureSet)
        {
            (rowElement[0] as Label).text = "0x" + clipRange.clipId.ToString("X16");

            string targetText = clipRange.targetId == 0u
                ? "(untargeted)"
                : "0x" + clipRange.targetId.ToString("X8");
            if (textureSet.TryGetPart(clipRange.targetId, out VatPartTextures matchedPart))
            {
                targetText += "  (" + PartDisplayName(matchedPart) + ")";
            }
            (rowElement[1] as Label).text = targetText;

            (rowElement[2] as Label).text = clipRange.frameStart.ToString();
            (rowElement[3] as Label).text = clipRange.frameCount.ToString();
            (rowElement[4] as Label).text = clipRange.fps.ToString("0.##");
        }

        // -----------------------------------------------------------------------------------
        // Socket tracks.
        // -----------------------------------------------------------------------------------

        private static VisualElement BuildSocketTrackSection(VatTextureSetAsset textureSet)
        {
            VisualElement container = new VisualElement();
            List<VatSocketTrack> socketTracks = textureSet.socketTracks;

            if (socketTracks == null || socketTracks.Count == 0)
            {
                container.Add(new Label(
                    "No socket tracks baked. Either this rig declares no bone sockets, or none were "
                    + "requested at bake time."));
                return container;
            }

            HashSet<uint> distinctSocketIds = new HashSet<uint>();
            int minSampleCount = int.MaxValue;
            int maxSampleCount = 0;
            for (int trackIndex = 0; trackIndex < socketTracks.Count; trackIndex++)
            {
                VatSocketTrack track = socketTracks[trackIndex];
                if (track == null)
                {
                    continue;
                }
                distinctSocketIds.Add(track.socketId);
                int sampleCount = track.positions != null ? track.positions.Count : 0;
                minSampleCount = Mathf.Min(minSampleCount, sampleCount);
                maxSampleCount = Mathf.Max(maxSampleCount, sampleCount);
            }
            if (minSampleCount == int.MaxValue)
            {
                minSampleCount = 0;
            }

            string sampleRangeText = minSampleCount == maxSampleCount
                ? minSampleCount.ToString()
                : minSampleCount.ToString() + " – " + maxSampleCount.ToString();
            Label summary = new Label(
                socketTracks.Count.ToString() + " track(s) across " + distinctSocketIds.Count.ToString()
                + " distinct socket(s). Samples per track:  " + sampleRangeText + ".");
            summary.style.whiteSpace = WhiteSpace.Normal;
            summary.style.marginBottom = 4f;
            container.Add(summary);

            float[] columnWidths = { 90f, 150f, 60f, 70f };
            container.Add(BuildTableHeaderRow(
                new string[] { "Socket Id", "Clip Id", "FPS", "Samples" }, columnWidths));

            ListView listView = new ListView { fixedItemHeight = TableRowHeight };
            listView.itemsSource = socketTracks;
            listView.makeItem = () => BuildTableRow(columnWidths);
            listView.bindItem = (VisualElement element, int index) => BindSocketTrackRow(element, socketTracks[index]);
            listView.style.height = Mathf.Min(TableRowHeight * socketTracks.Count, TableMaxHeight);
            listView.Rebuild();
            container.Add(listView);

            return container;
        }

        private static void BindSocketTrackRow(VisualElement rowElement, VatSocketTrack track)
        {
            if (track == null)
            {
                (rowElement[0] as Label).text = "—";
                (rowElement[1] as Label).text = "—";
                (rowElement[2] as Label).text = "—";
                (rowElement[3] as Label).text = "—";
                return;
            }
            (rowElement[0] as Label).text = "0x" + track.socketId.ToString("X8");
            (rowElement[1] as Label).text = "0x" + track.clipId.ToString("X16");
            (rowElement[2] as Label).text = track.fps.ToString("0.##");
            (rowElement[3] as Label).text = (track.positions != null ? track.positions.Count : 0).ToString();
        }

        // -----------------------------------------------------------------------------------
        // Shared table chrome.
        // -----------------------------------------------------------------------------------

        private static VisualElement BuildTableHeaderRow(string[] columnLabels, float[] columnWidths)
        {
            VisualElement row = new VisualElement();
            row.style.flexDirection = FlexDirection.Row;
            row.style.marginBottom = 2f;
            for (int columnIndex = 0; columnIndex < columnLabels.Length; columnIndex++)
            {
                Label label = new Label(columnLabels[columnIndex]);
                label.style.width = columnWidths[columnIndex];
                label.style.unityFontStyleAndWeight = FontStyle.Bold;
                row.Add(label);
            }
            return row;
        }

        private static VisualElement BuildTableRow(float[] columnWidths)
        {
            VisualElement row = new VisualElement();
            row.style.flexDirection = FlexDirection.Row;
            for (int columnIndex = 0; columnIndex < columnWidths.Length; columnIndex++)
            {
                Label label = new Label();
                label.selection.isSelectable = true;
                label.style.width = columnWidths[columnIndex];
                row.Add(label);
            }
            return row;
        }

        // -----------------------------------------------------------------------------------
        // Staleness.
        // -----------------------------------------------------------------------------------

        private static VisualElement BuildStalenessSection(VatTextureSetAsset textureSet)
        {
            VisualElement container = new VisualElement();

            Label hashLabel = new Label("Stored source hash:  0x" + textureSet.sourceHash.ToString("X16"));
            hashLabel.selection.isSelectable = true;
            container.Add(hashLabel);

            // No "stale" badge: recomputing the hash needs the source SkinnedMeshRenderer and
            // AnimationClips, and this asset does not retain those references after baking.
            HelpBox notice = new HelpBox(
                "Staleness cannot be checked from this inspector — recomputing the hash needs the "
                + "original skinned mesh and animation clips, which this asset does not retain after "
                + "the bake. Rebake through the button below whenever the source rig or clips change.",
                HelpBoxMessageType.Info);
            container.Add(notice);

            return container;
        }

        // -----------------------------------------------------------------------------------
        // Rebake.
        // -----------------------------------------------------------------------------------

        private static VisualElement BuildRebakeSection()
        {
            VisualElement container = new VisualElement();

            Button openBakeWindowButton = new Button(VatBakeWindow.ShowWindow) { text = "Open VAT Baker" };
            openBakeWindowButton.tooltip =
                "Opens the VAT Bake window. Re-assign the clip set and skinned mesh there and bake "
                + "again — the result overwrites this asset at its current path.";
            container.Add(openBakeWindowButton);

            return container;
        }
    }
}
