// Copyright (c) 2026 Stitch Punk. All rights reserved.

using System.Collections.Generic;
using StitchPunk.AnimationToolkit;
using StitchPunk.AnimationToolkit.Authoring;
using UnityEditor;
using UnityEditor.UIElements;
using UnityEngine;
using UnityEngine.UIElements;

namespace StitchPunk.AnimationToolkit.Editor
{
    /// <summary>
    /// The custom inspector for <see cref="VatTextureSetAsset"/> (architecture section 7.1):
    /// read-only bake statistics, per-clip frame ranges, socket track counts, and the one escape
    /// hatch back to the tool that produced the asset — the VAT Bake window.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <strong>Nothing here binds through <see cref="SerializedObject"/>.</strong> Every field on
    /// this asset is written by <c>VatTextureBaker</c> and is documented on the type itself as
    /// read-only by hand (see <see cref="VatTextureSetAsset"/>'s own doc comment). A bound, disabled
    /// <see cref="PropertyField"/> still renders as a field — a box with a border a user expects to
    /// be able to click into — which is exactly the impression a generated-output asset must not
    /// give. Reading <see cref="UnityEditor.Editor.target"/>'s values straight into
    /// <see cref="Label"/> text leaves nothing on screen shaped like an editable control, which is a
    /// stronger guarantee than a disabled one and costs nothing here because nothing needs Undo,
    /// dirtying, or prefab-override handling — the whole point of binding through
    /// <see cref="SerializedProperty"/> in the first place.
    /// </para>
    /// <para>
    /// UI Toolkit only, per section 7 and enforced by
    /// <c>PackagingConformanceTests.Conformance_E_NoImguiApis_InEditorSources</c>: this type
    /// overrides <see cref="UnityEditor.Editor.CreateInspectorGUI"/> and never the immediate-mode
    /// entry point.
    /// </para>
    /// </remarks>
    [CustomEditor(typeof(VatTextureSetAsset))]
    public sealed class VatTextureSetAssetEditor : UnityEditor.Editor
    {
        /// <summary>
        /// Bytes per texel for a format the baker never emits. A guess rather than a lie: better to
        /// flag the estimate as approximate than to silently pick one of the two real formats and
        /// risk reporting a number that looks exact but is not.
        /// </summary>
        private const int FallbackBytesPerTexel = 4;

        private const float TableRowHeight = 20f;
        private const float TableMaxHeight = 200f;

        /// <inheritdoc />
        public override VisualElement CreateInspectorGUI()
        {
            VatTextureSetAsset textureSet = target as VatTextureSetAsset;

            VisualElement root = new VisualElement();
            root.style.paddingTop = 4f;

            root.Add(BuildGeneratedAssetNotice());

            if (textureSet == null)
            {
                return root;
            }

            root.Add(BuildSectionHeading("Overview"));
            root.Add(BuildOverviewSection(textureSet));

            root.Add(BuildSectionHeading("Estimated GPU Memory"));
            root.Add(BuildMemorySection(textureSet));

            root.Add(BuildSectionHeading("Clip Ranges"));
            root.Add(BuildClipRangeSection(textureSet));

            root.Add(BuildSectionHeading("Socket Tracks"));
            root.Add(BuildSocketTrackSection(textureSet));

            root.Add(BuildSectionHeading("Staleness"));
            root.Add(BuildStalenessSection(textureSet));

            root.Add(BuildSectionHeading("Rebake"));
            root.Add(BuildRebakeSection());

            return root;
        }

        // -----------------------------------------------------------------------------------
        // Static chrome.
        // -----------------------------------------------------------------------------------

        private static Label BuildSectionHeading(string text)
        {
            Label heading = new Label(text);
            heading.style.unityFontStyleAndWeight = FontStyle.Bold;
            heading.style.marginTop = 10f;
            heading.style.marginBottom = 2f;
            return heading;
        }

        /// <summary>
        /// Leads the inspector with why every value below is unclickable.
        /// </summary>
        private static HelpBox BuildGeneratedAssetNotice()
        {
            return new HelpBox(
                "Generated by the VAT Texture Baker. Every field on this asset is written by the "
                + "bake and is not meant to be hand-edited: changing a frame range or a count here "
                + "still looks valid to Unity but produces a set that no longer matches its own "
                + "textures, and nothing downstream detects that — VatMaterialSystem just holds "
                + "whatever frame the mismatch lands on. Use \"Open VAT Baker\" below to regenerate "
                + "this asset instead of editing it.",
                HelpBoxMessageType.Info);
        }

        // -----------------------------------------------------------------------------------
        // Overview.
        // -----------------------------------------------------------------------------------

        private static VisualElement BuildOverviewSection(VatTextureSetAsset textureSet)
        {
            VisualElement container = new VisualElement();

            container.Add(new Label("Flavor:  " + textureSet.flavor.ToString()));
            container.Add(new Label(
                "Texture Width:  " + textureSet.textureWidth.ToString()
                + "     Rows / Frame:  " + textureSet.rowsPerFrame.ToString()));

            Label countLabel = textureSet.flavor == VatFlavor.BoneMatrix
                ? new Label("Bone Count:  " + textureSet.boneCount.ToString())
                : new Label("Vertex Count:  " + textureSet.vertexCount.ToString());
            container.Add(countLabel);

            container.Add(new Label("Schema Version:  " + textureSet.schemaVersion.ToString()));

            Label setKeyLabel = new Label("Set Key:  0x" + textureSet.SetKey.ToString("X16"));
            setKeyLabel.selection.isSelectable = true;
            container.Add(setKeyLabel);

            return container;
        }

        // -----------------------------------------------------------------------------------
        // Estimated GPU memory.
        // -----------------------------------------------------------------------------------

        private static VisualElement BuildMemorySection(VatTextureSetAsset textureSet)
        {
            VisualElement container = new VisualElement();

            Texture2D primaryTexture = textureSet.flavor == VatFlavor.BoneMatrix
                ? textureSet.boneTexture
                : textureSet.positionTexture;
            string primaryLabel = textureSet.flavor == VatFlavor.BoneMatrix
                ? "Bone Texture"
                : "Position Texture";

            long totalBytes = 0L;
            totalBytes += AddTextureMemoryRow(container, primaryLabel, primaryTexture);
            totalBytes += AddTextureMemoryRow(container, "Normal Texture", textureSet.normalTexture);

            if (totalBytes == 0L)
            {
                container.Add(new Label("No textures assigned."));
            }

            Label totalLabel = new Label("Total:  " + FormatBytes(totalBytes));
            totalLabel.style.unityFontStyleAndWeight = FontStyle.Bold;
            totalLabel.style.marginTop = 4f;
            container.Add(totalLabel);

            Label assumptionNote = new Label(
                "Estimated as width x height x bytes-per-texel for each texture's own TextureFormat. "
                + "VatTextureBaker.CreateTexture writes RGBAHalf (8 bytes/texel) unless the bake used "
                + "Full Precision, which writes RGBAFloat (16 bytes/texel) — those are the only two "
                + "formats the baker ever emits (Editor/VatBaking/VatTextureBaker.cs, Bake()). Any "
                + "other format reaching this inspector falls back to a conservative "
                + FallbackBytesPerTexel.ToString() + " bytes/texel rather than pretending certainty "
                + "this asset does not have.");
            assumptionNote.style.whiteSpace = WhiteSpace.Normal;
            assumptionNote.style.opacity = 0.7f;
            assumptionNote.style.marginTop = 2f;
            container.Add(assumptionNote);

            return container;
        }

        private static long AddTextureMemoryRow(VisualElement container, string label, Texture2D texture)
        {
            if (texture == null)
            {
                return 0L;
            }
            long byteCount = (long)texture.width * texture.height * BytesPerTexel(texture.format);
            Label rowLabel = new Label(
                label + "  (" + texture.format.ToString() + ", " + texture.width.ToString() + "x"
                + texture.height.ToString() + "):  " + FormatBytes(byteCount));
            container.Add(rowLabel);
            return byteCount;
        }

        private static int BytesPerTexel(TextureFormat format)
        {
            switch (format)
            {
                case TextureFormat.RGBAHalf:
                    // 4 channels x 16-bit float each.
                    return 8;
                case TextureFormat.RGBAFloat:
                    // 4 channels x 32-bit float each.
                    return 16;
                default:
                    return FallbackBytesPerTexel;
            }
        }

        private static string FormatBytes(long byteCount)
        {
            double megabytes = byteCount / (1024.0 * 1024.0);
            return megabytes.ToString("0.00") + " MB";
        }

        // -----------------------------------------------------------------------------------
        // Clip ranges.
        // -----------------------------------------------------------------------------------

        private static VisualElement BuildClipRangeSection(VatTextureSetAsset textureSet)
        {
            VisualElement container = new VisualElement();
            List<VatClipRange> clipRanges = textureSet.clipRanges;

            if (clipRanges == null || clipRanges.Count == 0)
            {
                container.Add(new Label("No clip ranges baked."));
                return container;
            }

            int totalFrames = 0;
            for (int rangeIndex = 0; rangeIndex < clipRanges.Count; rangeIndex++)
            {
                totalFrames += clipRanges[rangeIndex].frameCount;
            }
            Label summary = new Label(
                clipRanges.Count.ToString() + " clip(s), " + totalFrames.ToString() + " total frame(s).");
            summary.style.marginBottom = 4f;
            container.Add(summary);

            float[] columnWidths = { 150f, 90f, 90f, 60f };
            container.Add(BuildTableHeaderRow(
                new string[] { "Clip Id", "Frame Start", "Frame Count", "FPS" }, columnWidths));

            ListView listView = new ListView { fixedItemHeight = TableRowHeight };
            listView.itemsSource = clipRanges;
            listView.makeItem = () => BuildTableRow(columnWidths);
            listView.bindItem = (VisualElement element, int index) => BindClipRangeRow(element, clipRanges[index]);
            listView.style.height = Mathf.Min(TableRowHeight * clipRanges.Count, TableMaxHeight);
            listView.Rebuild();
            container.Add(listView);

            return container;
        }

        private static void BindClipRangeRow(VisualElement rowElement, VatClipRange clipRange)
        {
            (rowElement[0] as Label).text = "0x" + clipRange.clipId.ToString("X16");
            (rowElement[1] as Label).text = clipRange.frameStart.ToString();
            (rowElement[2] as Label).text = clipRange.frameCount.ToString();
            (rowElement[3] as Label).text = clipRange.fps.ToString("0.##");
        }

        // -----------------------------------------------------------------------------------
        // Socket tracks.
        // -----------------------------------------------------------------------------------

        private static VisualElement BuildSocketTrackSection(VatTextureSetAsset textureSet)
        {
            VisualElement container = new VisualElement();
            List<VatSocketTrack> socketTracks = textureSet.socketTracks;

            if (socketTracks == null || socketTracks.Count == 0)
            {
                container.Add(new Label(
                    "No socket tracks baked. Either this rig declares no bone sockets, or none were "
                    + "requested at bake time."));
                return container;
            }

            HashSet<uint> distinctSocketIds = new HashSet<uint>();
            int minSampleCount = int.MaxValue;
            int maxSampleCount = 0;
            for (int trackIndex = 0; trackIndex < socketTracks.Count; trackIndex++)
            {
                VatSocketTrack track = socketTracks[trackIndex];
                if (track == null)
                {
                    continue;
                }
                distinctSocketIds.Add(track.socketId);
                int sampleCount = track.positions != null ? track.positions.Count : 0;
                minSampleCount = Mathf.Min(minSampleCount, sampleCount);
                maxSampleCount = Mathf.Max(maxSampleCount, sampleCount);
            }
            if (minSampleCount == int.MaxValue)
            {
                minSampleCount = 0;
            }

            string sampleRangeText = minSampleCount == maxSampleCount
                ? minSampleCount.ToString()
                : minSampleCount.ToString() + " – " + maxSampleCount.ToString();
            Label summary = new Label(
                socketTracks.Count.ToString() + " track(s) across " + distinctSocketIds.Count.ToString()
                + " distinct socket(s). Samples per track:  " + sampleRangeText + ".");
            summary.style.whiteSpace = WhiteSpace.Normal;
            summary.style.marginBottom = 4f;
            container.Add(summary);

            float[] columnWidths = { 90f, 150f, 60f, 70f };
            container.Add(BuildTableHeaderRow(
                new string[] { "Socket Id", "Clip Id", "FPS", "Samples" }, columnWidths));

            ListView listView = new ListView { fixedItemHeight = TableRowHeight };
            listView.itemsSource = socketTracks;
            listView.makeItem = () => BuildTableRow(columnWidths);
            listView.bindItem = (VisualElement element, int index) => BindSocketTrackRow(element, socketTracks[index]);
            listView.style.height = Mathf.Min(TableRowHeight * socketTracks.Count, TableMaxHeight);
            listView.Rebuild();
            container.Add(listView);

            return container;
        }

        private static void BindSocketTrackRow(VisualElement rowElement, VatSocketTrack track)
        {
            if (track == null)
            {
                (rowElement[0] as Label).text = "—";
                (rowElement[1] as Label).text = "—";
                (rowElement[2] as Label).text = "—";
                (rowElement[3] as Label).text = "—";
                return;
            }
            (rowElement[0] as Label).text = "0x" + track.socketId.ToString("X8");
            (rowElement[1] as Label).text = "0x" + track.clipId.ToString("X16");
            (rowElement[2] as Label).text = track.fps.ToString("0.##");
            (rowElement[3] as Label).text = (track.positions != null ? track.positions.Count : 0).ToString();
        }

        // -----------------------------------------------------------------------------------
        // Shared table chrome.
        // -----------------------------------------------------------------------------------

        private static VisualElement BuildTableHeaderRow(string[] columnLabels, float[] columnWidths)
        {
            VisualElement row = new VisualElement();
            row.style.flexDirection = FlexDirection.Row;
            row.style.marginBottom = 2f;
            for (int columnIndex = 0; columnIndex < columnLabels.Length; columnIndex++)
            {
                Label label = new Label(columnLabels[columnIndex]);
                label.style.width = columnWidths[columnIndex];
                label.style.unityFontStyleAndWeight = FontStyle.Bold;
                row.Add(label);
            }
            return row;
        }

        private static VisualElement BuildTableRow(float[] columnWidths)
        {
            VisualElement row = new VisualElement();
            row.style.flexDirection = FlexDirection.Row;
            for (int columnIndex = 0; columnIndex < columnWidths.Length; columnIndex++)
            {
                Label label = new Label();
                label.selection.isSelectable = true;
                label.style.width = columnWidths[columnIndex];
                row.Add(label);
            }
            return row;
        }

        // -----------------------------------------------------------------------------------
        // Staleness.
        // -----------------------------------------------------------------------------------

        /// <summary>
        /// Shows the stored hash and explains, honestly, why this inspector cannot say whether it is
        /// current.
        /// </summary>
        /// <remarks>
        /// <strong>Why there is no "stale" indicator here.</strong>
        /// <c>VatTextureBaker.ComputeSourceHash</c> folds in the flavor, sample rate, element count,
        /// total frame count, full-precision flag, and per clip the clip id, loop-safe flag, and the
        /// source <c>AnimationClip</c>'s length and name — none of which <see cref="VatTextureSetAsset"/>
        /// retains after the bake completes. The asset keeps the textures, the ranges, and the hash
        /// itself, but not the <c>SkinnedMeshRenderer</c> or the <c>AnimationClip</c> references the
        /// hash was computed from, so there is nothing here to recompute the hash against. A badge
        /// that always read "up to date" — or that guessed from unrelated signals like the asset's
        /// import timestamp — would be wrong exactly when it matters most, and a false "up to date"
        /// is worse than admitting the check cannot be done from this window.
        /// </remarks>
        private static VisualElement BuildStalenessSection(VatTextureSetAsset textureSet)
        {
            VisualElement container = new VisualElement();

            Label hashLabel = new Label("Stored source hash:  0x" + textureSet.sourceHash.ToString("X16"));
            hashLabel.selection.isSelectable = true;
            container.Add(hashLabel);

            HelpBox notice = new HelpBox(
                "Staleness cannot be checked from this inspector — recomputing the hash needs the "
                + "original skinned mesh and animation clips, which this asset does not retain after "
                + "the bake (validation rule V08 detects staleness only by comparing against a fresh "
                + "bake's hash). Rebake through the button below whenever the source rig or clips "
                + "change.",
                HelpBoxMessageType.Info);
            container.Add(notice);

            return container;
        }

        // -----------------------------------------------------------------------------------
        // Rebake.
        // -----------------------------------------------------------------------------------

        private static VisualElement BuildRebakeSection()
        {
            VisualElement container = new VisualElement();

            Button openBakeWindowButton = new Button(VatBakeWindow.ShowWindow) { text = "Open VAT Baker" };
            openBakeWindowButton.tooltip =
                "Opens the VAT Bake window. Re-assign the clip set and skinned mesh there and bake "
                + "again — the result overwrites this asset at its current path.";
            container.Add(openBakeWindowButton);

            return container;
        }
    }
}
