// Generated by the DOTS Animation Toolkit Events tab, then converted off the removed routing table.
// This is your code now: reads the Damage key straight from each actor's event buffer.
using Unity.Burst;
using Unity.Collections;
using Unity.Entities;
using DotsAnimationToolkit;

[BurstCompile]
// Place after EventEmissionSystem
public partial struct DamageEventSystemAnimEventSystem : ISystem
{
    [BurstCompile]
    public void OnUpdate(ref SystemState state)
    {
        state.Dependency = new DamageEventSystemJob().ScheduleParallel(state.Dependency);
    }
}

[BurstCompile]
[WithAll(typeof(AnimEventsPending))]
public partial struct DamageEventSystemJob : IJobEntity
{
    public void Execute(in DynamicBuffer<AnimEventOutput> events)
    {
        // Two layers can emit the same key in one frame, so every match is visited, not just the first.
        int searchIndex = 0;
        while (AnimEventBufferApi.TryFindNextEvent(events, AnimEvents.Damage, ref searchIndex, out AnimEventOutput damageEvent))
        {
            // TODO: apply damage (damageEvent.intParam / floatParam carry the payload).
        }
    }
}
